name: On the 50 road
favicon: null
layout_spectrum: 0.72838
typography_spectrum: 0.33110063266940415
title: On the 50 road
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdffde'
    - '#450019'
    - '#d5009b'
    - '#ca96a2'
    - '#00a586'
  brandStrength: 0.20597862266004086
  lightness: 0.9355023617390543
  saturation: 0.4689981499686837
  rhythmicContrast: 0.19077890180051327
purpose: []
