name: On the 50 road
favicon: null
layout_spectrum: 0.025849496014416218
typography_spectrum: 0.33110063266940415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20597862266004086
  lightness: 0.9355023617390543
  saturation: 0.4689981499686837
  rhythmicContrast: 0.19077890180051327
purpose: []
